import { getCurrencyInfo } from 'libs/currency-info';

export default [
  {
    ticker: 'btc',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: true,
  },
  {
    ticker: 'bch',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: true,
  },
  {
    ticker: 'btg',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: true,
  },
  {
    ticker: 'eth',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: true,
  },
  {
    ticker: 'etc',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: true,
  },
  {
    ticker: 'ltc',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: true,
  },
  {
    ticker: 'doge',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: false,
  },
  {
    ticker: 'zec',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: true,
  },
  {
    ticker: 'xrp',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: false,
    android: false,
  },
  {
    ticker: 'dash',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: false,
  },
  {
    ticker: 'clo',
    ladgerBlue: false,
    ladgerNano: false,
    trezor: false,
    android: true,
  },
  {
    ticker: 'strat',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: false,
    android: false,
  },
  {
    ticker: 'kmd',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: false,
    android: true,
  },
  {
    ticker: 'exp',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: false,
  },
  {
    ticker: 'ubq',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: true,
    android: false,
  },
  {
    ticker: 'vtc',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: false,
    android: false,
  },
  {
    ticker: 'via',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: false,
    android: false,
  },
  {
    ticker: 'neo',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: false,
    android: false,
  },
  {
    ticker: 'qtum',
    ladgerBlue: true,
    ladgerNano: true,
    trezor: false,
    android: true,
  },
].map((item) => {
  const info = getCurrencyInfo(item.ticker);
  return Object.assign({}, item, info);
});
